### ISSUE TITLE
adafruit-circuitpython-apds9500 is not published to PyPi

### ISSUE THREAD

**Issue by Gadgetoid** [adafruit/Adafruit_CircuitPython_APDS9500#7]
As per the instructions in the `README.md` I attempted to do the following on a Raspberry Pi:
```
pip3 install adafruit-circuitpython-apds9500
```

Which resulted in:
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement adafruit-circuitpython-apds9500 (from versions: none)
ERROR: No matching distribution found for adafruit-circuitpython-apds9500
```

Looks like it needs published to PyPi but I'm not sure if you abandoned the APDS9500 because it's too similar to the APDS9960? Either way, it would be a shame to let this code rot!

Thank you.

**Comment by ladyada** [comment]
hi we're still evaluating the APDS9500 sensor breakout - you can install this library manually until we deem it releasable code :)

**Comment by Gadgetoid** [comment]
Thanks for letting me know! In the interest of full disclosure I've got a Breakout Garden ready board hosting the APDS9500 that would benefit from this library. Happy to review, test, feedback and help where I can.

It's a delightfully complicated chip to be sure.

It looks like this library has a simple gesture demo (which works for me) but is missing Proximity, Cursor (perhaps the one I find most interesting) and Image output modes. The latter might be out of scope/feasibility for CircuitPython (albeit it's only max 60x60@9bpp) but if it wouldn't be a duplication of effort for me to have a go at bringing either of these online, let me know!

**Comment by ladyada** [comment]
yep we'd love any contributions - better to have one library than 2 separate efforts :) proximity/cursor and image output are definitely interesting! We can accelerate releasing this as 1.0.0 to pypi if that would help

**Comment by evaherrada** [comment]
Closing because this appears more or less resolved
